import type { ClinicalContext, MealItem, Result } from '../../domain/types.js';
import { normalizePortion, runNutrientPipeline } from '../engine.js';
export type ModelStage = 'GROSS_ONLY' | 'ABSORPTION_MODELED' | 'CONVERSION_MODELED';
export interface NutrientPipelineResult { nutrientKey: string; modelStage: ModelStage; gross: Result; chemicalForms: Record<string, number>; bioaccessible: Result | null; absorbed: Result | null; systemic: Result | null; converted: Result | null; active: Result | null; targetComparison: null; sourceContributions: Record<string, number>; unavailableReason: string | null; }
/** Canonical orchestration: it never turns unavailable physiology into a zero. */
export function calculateNutrientPipeline(items: MealItem[], context: ClinicalContext): NutrientPipelineResult[] {
 const entries=items.flatMap(item=>item.food.nutrients.flatMap(n=>{const retention=item.preparation?.retention[n.form.nutrientKey];const normalized=normalizePortion(n.amountPer100g,item.grams,(item.preparation?{yield:{min:item.preparation.yieldMin,max:item.preparation.yieldMax,evidenceId:`yield:${item.preparation.method}`},...(retention?{retention}:{})}:null) as never);return normalized.reason?.startsWith('Nutrient-specific')?[]:[{nutrientKey:n.form.nutrientKey,formId:n.form.id,origin:n.form.origin,foodBound:n.form.foodBound,amount:normalized.amount,unit:n.unit,yieldFactor:normalized.yieldFactor,retentionFactor:normalized.retentionFactor}]}));
 return runNutrientPipeline(entries,context,{}).map(total=>{const modeled=total.absorption.status==='modeled';return{nutrientKey:total.nutrientKey,modelStage:modeled?'ABSORPTION_MODELED':'GROSS_ONLY',gross:{value:total.grossIntake.value,unit:total.unit,status:'estimated',confidence:'moderate',evidenceIds:[],assumptions:[],warnings:[]},chemicalForms:total.chemicalForm.amounts,bioaccessible:null,absorbed:modeled?{min:total.absorption.min,max:total.absorption.max,unit:total.unit,status:'modeled',confidence:'low',evidenceIds:total.absorption.modelKeys,assumptions:[],warnings:[]}:null,systemic:null,converted:null,active:null,targetComparison:null,sourceContributions:total.sources,unavailableReason:modeled?total.systemicPool.reason:total.absorption.reason}});
}
export function assertFiniteNonNegative(value: number, label: string): void { if (!Number.isFinite(value) || value < 0) throw new Error(`${label} must be a finite non-negative number.`); }
