import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
const app=readFileSync('public/app.js','utf8'),service=readFileSync('public/application/meal-service.js','utf8');
test('all required local workspace controls are functionally bound',()=>{for(const token of ["$('add').onclick","[data-edit]","[data-remove]","$('clear').onclick","save-supplement","save-biomarker","save-targets","save-settings","clear-history","language-setting","gastric-acid","data-detail","repository.replace"])assert.ok(app.includes(token),token);});
test('UI exposes gross, absorbed, source form, uncertainty, and unmodeled stages',()=>{for(const phrase of ['Actual gross intake','Total estimated absorbed','Food-bound','Free/crystalline','Heme','Non-heme','Bioaccessible, systemic, converted, and active stages remain unmodeled'])assert.ok((app+service).includes(phrase),phrase);});
test('localized paths translate static chrome, rendered views, modal text, and notices',()=>{const index=readFileSync('public/index.html','utf8');for(const phrase of ['nutrition intelligence','Local workspace','Private browser storage','LIVE ANALYSIS','Meal signals','MODEL BOUNDARIES'])assert.ok(index.includes(`data-i18n="${phrase}"`),phrase);assert.match(app,/innerHTML=translateMarkup\(html,state.language\)/);assert.match(app,/innerHTML=translateMarkup\(`<span/);assert.equal(app.match(/\$\('notice'\)\.textContent=/g)?.length,1)});
test('personalization UI exposes state-aware hypochlorhydria and celiac limitations',()=>{for(const phrase of ['hypochlorhydria-state','celiac-state','Documented hypochlorhydria','Active / untreated','Treated / adherent gluten-free diet','Mechanism recognized, but no defensible individual quantitative coefficient is applied.'])assert.ok(app.includes(phrase),phrase);});

test('personalization UI exposes Crohn anatomical state and UC activity state',()=>{for(const phrase of ['crohn-state','ulcerative-colitis-state','Active disease with ileal involvement','Remission without reported ileal involvement','Ulcerative colitis state'])assert.ok(app.includes(phrase),phrase);});
test('personalization UI exposes documented PEI, PERT boundary, and procedure-specific bariatric choices',()=>{for(const phrase of ['pei-state','Documented PEI','enzyme replacement context','bariatric-surgery-state','Roux-en-Y gastric bypass (RYGB)','Sleeve gastrectomy (SG)','Biliopancreatic diversion / duodenal switch (BPD/DS)','does not create a generic surgery multiplier'])assert.ok(app.includes(phrase),phrase);});
