// @ts-nocheck
/** Canonical calculation authority. This file is deliberately valid JavaScript: sync:engine publishes it verbatim. */
export const MODEL_PARAMETERS=Object.freeze({
 ironHeme:Object.freeze({modelKey:'iron.heme.absorption_range.v1',min:.15,max:.35,unit:'mg'}),
 ironNonHeme:Object.freeze({modelKey:'iron.nonheme.absorption_range.v1',min:.03,max:.12,unit:'mg'}),
 b12Food:Object.freeze({modelKey:'b12.food_bound.absorption_range.v1',min:.30,max:.60,unit:'µg'}),
 b12Free:Object.freeze({modelKey:'b12.free.absorption_range.v1',min:.30,max:.60,unit:'µg'}),
 // Miller et al. fit: mmol/day. It estimates population total absorption, not ZIP4 expression.
 zincMiller2007:Object.freeze({modelKey:'zinc.miller.phytate.saturation.v1',aMax:.091,kr:.680,kp:.033,zincMolarMassMg:65.38,phytateMolarMassMg:660.04}),
 thiamine:Object.freeze({modelKey:'thiamine.energy.optimization.v1',minPerKcal:.00060,maxPerKcal:.00068}),
 pral:Object.freeze({modelKey:'pral.remer_manz.v1',protein:.49,phosphorus:.037,potassium:-.021,magnesium:-.026,calcium:-.013})
});

/** Condition data names mechanisms and evidence; it never contains a blanket disease multiplier. */
export const CONDITION_CATALOG=Object.freeze([
 {id:'hypochlorhydria',name:'Low gastric acid / hypochlorhydria',description:'Use only for documented low acid or a known acid-suppressing context; symptoms alone are not diagnostic.',inputs:['state: suspected, documented, acid_suppression, achlorhydria'],effects:[
  {mechanismId:'gastric-acid.food-release',stage:'absorption',nutrients:['vitamin_b12'],type:'reduced_absorption',quantitative:false,evidenceClass:'B',source:'iom-b12-dri',assumption:'Food-bound B12 can be affected; free/crystalline B12 is not assigned this effect.'},
  {mechanismId:'gastric-acid.nonheme-solubilization',stage:'absorption',nutrients:['iron'],type:'reduced_absorption',quantitative:false,evidenceClass:'B',source:'hurrell-egli-2010',assumption:'Non-heme iron mechanism only; no numeric low-acid multiplier is available.'}]},
 {id:'celiac_disease',name:'Celiac disease',description:'Diagnosis/treatment state changes clinical risk; this calculator does not diagnose celiac disease.',inputs:['state: untreated, treated_adherent, persistent_symptoms'],effects:[{mechanismId:'celiac.mucosal-malabsorption',stage:'absorption',nutrients:['iron','folate','vitamin_b12','vitamin_d'],type:'reduced_absorption',quantitative:false,evidenceClass:'B',source:'acg-celiac-guideline-2023',assumption:'Clinical deficiency risk is represented without a fabricated absorption coefficient.'}]},
 {id:'crohn_disease',name:"Crohn's disease",description:'Effects depend on activity, site, and resection.',inputs:['activity: active, remission','ileal involvement','ileal resection'],effects:[{mechanismId:'crohn.ileal-or-mucosal-malabsorption',stage:'absorption',nutrients:['vitamin_b12','iron','vitamin_d'],type:'reduced_absorption',quantitative:false,evidenceClass:'B',source:'aga-ibd-nutrition-2024',assumption:'Requires clinical context; no universal Crohn’s coefficient.'}]},
 {id:'ulcerative_colitis',name:'Ulcerative colitis',description:'Risk is context-dependent, especially during active disease.',inputs:['activity: active, remission'],effects:[{mechanismId:'ibd.inflammation-loss-or-intake',stage:'loss',nutrients:['iron','vitamin_d'],type:'increased_loss_excretion',quantitative:false,evidenceClass:'B',source:'aga-ibd-nutrition-2024',assumption:'Association/risk only; no intake multiplier.'}]},
 {id:'pancreatic_exocrine_insufficiency',name:'Pancreatic exocrine insufficiency',description:'Fat digestion impairment requires clinical evaluation.',inputs:['documented diagnosis','enzyme replacement context'],effects:[{mechanismId:'pei.fat-digestion',stage:'absorption',nutrients:['vitamin_a','vitamin_d','vitamin_e','vitamin_k'],type:'reduced_absorption',quantitative:false,evidenceClass:'B',source:'aga-epi-update-2023',assumption:'No numerical coefficient is applied.'}]},
 {id:'bariatric_bypass',name:'Bariatric surgery / gastric bypass',description:'Use the surgery type selected with a clinician’s follow-up plan.',inputs:['surgery type','relevant anatomy'],effects:[{mechanismId:'bariatric.anatomy-and-intake',stage:'absorption',nutrients:['iron','vitamin_b12','vitamin_d','calcium'],type:'reduced_absorption',quantitative:false,evidenceClass:'B',source:'asmbs-nutrition-guidelines-2016',assumption:'Guideline monitoring is not a personalized coefficient.'}]},
 {id:'ileal_resection',name:'Ileal resection',description:'Extent and remaining anatomy are clinically material.',inputs:['extent where known'],effects:[{mechanismId:'ileum.b12-bile-salt-absorption',stage:'absorption',nutrients:['vitamin_b12','vitamin_d','vitamin_a','vitamin_e','vitamin_k'],type:'reduced_absorption',quantitative:false,evidenceClass:'B',source:'short-bowel-guideline-2023',assumption:'No resection-length conversion is inferred.'}]},
 {id:'gastrectomy',name:'Gastrectomy',description:'Anatomy and intrinsic-factor status need clinical assessment.',inputs:['partial or total'],effects:[{mechanismId:'gastrectomy.gastric-processing',stage:'absorption',nutrients:['vitamin_b12','iron'],type:'reduced_absorption',quantitative:false,evidenceClass:'B',source:'gastric-surgery-nutrition-review',assumption:'Overlaps gastric-acid food-release mechanisms and is deduplicated.'}]},
 {id:'short_bowel_syndrome',name:'Short bowel syndrome',description:'Effects vary by anatomy, colon continuity, and adaptation.',inputs:['remaining anatomy'],effects:[{mechanismId:'short-bowel.reduced-surface-area',stage:'absorption',nutrients:['iron','vitamin_b12','vitamin_d','magnesium'],type:'reduced_absorption',quantitative:false,evidenceClass:'B',source:'short-bowel-guideline-2023',assumption:'Specialist-managed; no universal coefficient.'}]},
 {id:'chronic_kidney_disease',name:'Chronic kidney disease',description:'Metabolism and targets require stage- and lab-specific clinical guidance.',inputs:['stage if known'],effects:[{mechanismId:'ckd.renal-vitamin-d-activation',stage:'conversion',nutrients:['vitamin_d'],type:'impaired_conversion',quantitative:false,evidenceClass:'B',source:'kdigo-ckd-mbd-2017',assumption:'No dietary-to-calcitriol conversion is calculated.'}]},
 {id:'chronic_liver_disease',name:'Chronic liver disease',description:'Severity and etiology materially change nutrient metabolism.',inputs:['severity if known'],effects:[{mechanismId:'liver.nutrient-metabolism',stage:'conversion',nutrients:['vitamin_d','vitamin_a'],type:'impaired_conversion',quantitative:false,evidenceClass:'B',source:'espens-liver-guideline-2019',assumption:'No universal liver-disease multiplier.'}]}
]);
export function resolveConditionEffects(conditions=[]){const selected=conditions.map(x=>typeof x==='string'?{id:x}:x).filter(x=>CONDITION_CATALOG.some(c=>c.id===x.id));const seen=new Set;const effects=[];for(const selectedCondition of selected){const condition=CONDITION_CATALOG.find(c=>c.id===selectedCondition.id);for(const effect of condition.effects){const overlap=effect.mechanismId==='gastrectomy.gastric-processing'&&seen.has('gastric-acid.food-release');if(!overlap&&!seen.has(effect.mechanismId)){effects.push({...effect,conditionId:condition.id,conditionName:condition.name,input:selectedCondition.state??null});seen.add(effect.mechanismId)}}}return effects}

export function normalizePortion(amountPer100g,grams,preparation=null){if(!Number.isFinite(amountPer100g)||amountPer100g<0||!Number.isFinite(grams)||grams<0)throw Error('Amounts and grams must be finite and non-negative.');const base=amountPer100g*grams/100;if(!preparation)return{amount:base,yieldFactor:null,retentionFactor:null,evidenceIds:[],reason:null};const y=preparation.yield;if(!y)return{amount:base,yieldFactor:null,retentionFactor:null,evidenceIds:[],reason:'Preparation yield is unavailable; composition remains on its stated basis.'};const yieldFactor=(y.min+y.max)/2;const retention=preparation.retention;if(!retention)return{amount:base*yieldFactor,yieldFactor,retentionFactor:null,evidenceIds:[y.evidenceId],reason:'Nutrient-specific retention is unavailable; retained amount is unavailable.'};const retentionFactor=(retention.min+retention.max)/2;return{amount:base*yieldFactor*retentionFactor,yieldFactor,retentionFactor,evidenceIds:[y.evidenceId,retention.evidenceId],reason:null}}
export function estimateZincAbsorption(zincMg,phytateMg){if(!Number.isFinite(zincMg)||zincMg<0||!Number.isFinite(phytateMg)||phytateMg<0)throw Error('Zinc and phytate inputs must be finite and non-negative.');const p=MODEL_PARAMETERS.zincMiller2007,z=zincMg/p.zincMolarMassMg,phy=phytateMg/p.phytateMolarMassMg,term=p.aMax+z+p.kr*(1+phy/p.kp),absorbedMmol=(term-Math.sqrt(term*term-4*p.aMax*z))/2;return{value:round(absorbedMmol*p.zincMolarMassMg),unit:'mg/day',status:'modeled',modelKey:p.modelKey,confidence:'low',assumption:'Miller 2007 adult population model using daily dietary zinc and phytate; not an individual ZIP4-expression measurement.'}}
export function estimateFormAbsorption(key,origin,foodBound,amount,gastricAcid='normal',formId=''){if(key==='iron'){const explicitHeme=formId.includes('heme')&&!formId.includes('nonheme'),explicitNonHeme=formId.includes('nonheme');if(formId&&!explicitHeme&&!explicitNonHeme)return null;const nonHeme=explicitNonHeme||(!formId&&origin!=='animal'),p=nonHeme?MODEL_PARAMETERS.ironNonHeme:MODEL_PARAMETERS.ironHeme;return{min:amount*p.min,max:amount*p.max,unit:p.unit,modelKey:p.modelKey,assumption:nonHeme?(gastricAcid==='normal'?'Non-heme population range; no gastric-acid adjustment applies.':'Low gastric acid may affect non-heme iron, but no defensible numeric multiplier is enabled.'):'Heme iron has no gastric-acid penalty.'}}if(key==='vitamin_b12'){const p=foodBound?MODEL_PARAMETERS.b12Food:MODEL_PARAMETERS.b12Free;return{min:amount*p.min,max:amount*p.max,unit:p.unit,modelKey:p.modelKey,assumption:foodBound?(gastricAcid==='normal'?'Food-bound population range; intrinsic-factor capacity is not modeled.':'Low gastric acid may impair food-bound release, but no defensible numeric multiplier is enabled; intrinsic-factor capacity is not modeled.'):'Free/crystalline B12 has no food-protein release penalty.'}}return null}
export function calculateCanonical(entries,context={gastricAcid:'normal'}){const totals={};for(const entry of entries){const current=totals[entry.nutrientKey]??={nutrientKey:entry.nutrientKey,unit:entry.unit,gross:0,sources:{},forms:{},contributions:[],absorbedParts:[],unavailableReasons:[]};current.gross+=entry.amount;current.sources[entry.origin]=(current.sources[entry.origin]??0)+entry.amount;current.forms[entry.formId]=(current.forms[entry.formId]??0)+entry.amount;current.contributions.push(entry);const absorbed=estimateFormAbsorption(entry.nutrientKey,entry.origin,entry.foodBound===true,entry.amount,context.gastricAcid,entry.formId);if(absorbed)current.absorbedParts.push(absorbed);else current.unavailableReasons.push(entry.nutrientKey==='iron'&&entry.formId==='iron_total'?'Total FDC iron has no defensible heme/non-heme split; absorption is unavailable.':'Quantitative absorption is not modeled for this nutrient.');totals[entry.nutrientKey]=current}if(context.zincModelScope==='daily'&&totals.zinc){const model=estimateZincAbsorption(context.dietaryZincMg??totals.zinc.gross,context.phytateMg??0);totals.zinc.absorbedParts=[{min:model.value,max:model.value,unit:'mg',modelKey:model.modelKey}]}return Object.values(totals).map(total=>({...total,absorbed:total.absorbedParts.length?{min:total.absorbedParts.reduce((sum,x)=>sum+x.min,0),max:total.absorbedParts.reduce((sum,x)=>sum+x.max,0),unit:total.unit,status:'modeled',modelKeys:[...new Set(total.absorbedParts.map(x=>x.modelKey))]}:null}))}
export function describeMealInteractions(nutrientKey,modifiers={}){const observations=[];if(nutrientKey==='iron'&&modifiers.vitaminCMg>0)observations.push({modelKey:'iron.nonheme.vitamin_c.qualitative.v1',effect:'may increase non-heme iron absorption',quantitative:false,evidenceId:'hurrell-egli-2010'});if(['iron','zinc','calcium'].includes(nutrientKey)&&modifiers.phytateMg>0)observations.push({modelKey:'minerals.phytate.qualitative.v1',effect:'may reduce mineral bioaccessibility',quantitative:false,evidenceId:'hurrell-egli-2010'});if(nutrientKey==='copper'&&modifiers.supplementalZincMg>=50)observations.push({modelKey:'zinc.copper.high_supplement.qualitative.v1',effect:'sustained supplemental zinc at or above the adult UL may impair copper absorption; gross copper is unchanged',quantitative:false,evidenceId:'iom-zinc-dri'});if(nutrientKey==='vitamin_d'&&modifiers.magnesiumStatus==='low')observations.push({modelKey:'magnesium.vitamin_d.activation.qualitative.v1',effect:'Low magnesium availability may impair vitamin-D metabolism; no activation coefficient is applied.',quantitative:false,evidenceId:'magnesium-vitamin-d-review'});if(nutrientKey==='thiamine'&&modifiers.magnesiumStatus==='low')observations.push({modelKey:'magnesium.thiamine.utilization.qualitative.v1',effect:'Magnesium is a cofactor for thiamine utilization; this is not a TTFD magnesium drain.',quantitative:false,evidenceId:'thiamine-magnesium-review'});return observations}
export function runNutrientPipeline(entries,context={gastricAcid:'normal'},targets={}){const conditionEffects=resolveConditionEffects(context.conditions??[]);return calculateCanonical(entries,context).map(total=>{const target=targets[total.nutrientKey],observations=describeMealInteractions(total.nutrientKey,context.mealModifiers);return{nutrientKey:total.nutrientKey,unit:total.unit,portionNormalization:{status:'calculated',contributions:total.contributions},preparationYield:{status:total.contributions.some(x=>x.yieldFactor!=null)?'calculated':'unavailable',reason:total.contributions.some(x=>x.yieldFactor!=null)?null:'No evidence-linked preparation yield was supplied.'},nutrientRetention:{status:total.contributions.some(x=>x.retentionFactor!=null)?'calculated':'unavailable',reason:total.contributions.some(x=>x.retentionFactor!=null)?null:'No evidence-linked nutrient-specific retention was supplied.'},chemicalForm:{status:'identified',amounts:total.forms},grossIntake:{status:'calculated',value:total.gross,unit:total.unit},mealInteractions:{status:'qualitative',multiplier:null,observations,reason:'No enabled quantitative meal interaction applies; observations do not change the numeric result.'},conditionEffects:conditionEffects.filter(x=>x.nutrients.includes(total.nutrientKey)),bioaccessibility:{status:'unavailable',value:null,reason:'No separate quantitative bioaccessibility model is enabled.'},absorption:total.absorbed??{status:'unavailable',value:null,reason:total.unavailableReasons[0]},systemicPool:{status:'unavailable',value:null,reason:'Systemic distribution cannot be inferred from meal intake.'},conversion:{status:'unavailable',value:null,reason:'No nutrient-specific conversion model is enabled.'},activePool:{status:'unavailable',value:null,reason:'Active intracellular pool cannot be inferred from intake.'},targetComparison:target?{status:'calculated',actual:total.gross,target,unit:total.unit}:{status:'unavailable',value:null,reason:'No applicable target record was supplied.'},sources:total.sources,contributions:total.contributions}})}
export function thiamineTarget(energyKcal){if(!Number.isFinite(energyKcal)||energyKcal<0)throw Error('Energy must be finite and non-negative.');return{min:round(energyKcal*MODEL_PARAMETERS.thiamine.minPerKcal),max:round(energyKcal*MODEL_PARAMETERS.thiamine.maxPerKcal),modelKey:MODEL_PARAMETERS.thiamine.modelKey}}
export function progressScale(actual,target){const values=[actual,target.rda,target.ai,target.pri,target.ear,target.ar,target.optimalMin,target.optimalMax,target.ul].filter(v=>typeof v==='number'&&v>=0),scale=Math.max(1,...values)*1.12;return{scale,actual:actual/scale*100,markers:Object.fromEntries(Object.entries(target).filter(([,v])=>typeof v==='number').map(([k,v])=>[k,v/scale*100]))}}
export function calculatePral(input){const p=MODEL_PARAMETERS.pral;return p.protein*input.proteinG+p.phosphorus*input.phosphorusMg+p.potassium*input.potassiumMg+p.magnesium*input.magnesiumMg+p.calcium*input.calciumMg}
const round=value=>Math.round(value*1000)/1000;
