#!/usr/bin/env node
import {readFile,writeFile} from'node:fs/promises';
const [inputPath,outputPath='public/canonical-foods.json',reportPath='data/fdc-resolution-report.json']=process.argv.slice(2);
if(!inputPath){console.error('Usage: node scripts/import-fdc.mjs <official-fdc-json> [canonical-output] [resolution-report]');process.exit(2)}
const manifest=JSON.parse(await readFile('data/fdc-food-manifest.json','utf8'));const targets=JSON.parse(await readFile('data/reference-targets.json','utf8'));const source=JSON.parse(await readFile(inputPath,'utf8'));const records=Array.isArray(source)?source:(source.foods??[]);
const normalize=x=>x.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();const preferred=new Map([['Foundation',3],['SR Legacy',2],['Survey (FNDDS)',1]]);
const nutrientMap=new Map([[1008,['energy','kcal']],[1003,['protein','g']],[1004,['fat','g']],[1005,['carbohydrate','g']],[1079,['fiber','g']],[1087,['calcium','mg']],[1089,['iron_total','mg']],[1092,['potassium','mg']],[1095,['zinc','mg']],[1162,['vitamin_c','mg']],[1165,['thiamine','mg']],[1178,['vitamin_b12_food','µg']]]);
const canonicalForms={fiber:{nutrientKey:'fiber',origin:'plant',label:'Dietary fiber'},calcium:{nutrientKey:'calcium',origin:'plant',label:'Calcium'},iron_total:{nutrientKey:'iron',origin:'plant',label:'Total iron; heme fraction unavailable'},potassium:{nutrientKey:'potassium',origin:'plant',label:'Potassium'},zinc:{nutrientKey:'zinc',origin:'plant',label:'Zinc'},vitamin_c:{nutrientKey:'vitamin_c',origin:'plant',label:'Vitamin C'},thiamine:{nutrientKey:'thiamine',origin:'plant',label:'Thiamine'},vitamin_b12_food:{nutrientKey:'vitamin_b12',origin:'animal',foodBound:true,label:'Food-bound vitamin B12'}};
const basis=d=>/raw/i.test(d)?'raw':/(cooked|roasted|boiled|baked|canned|brewed)/i.test(d)?'cooked':'ready_to_eat';
const words=s=>new Set(normalize(s).split(' '));const score=(query,record)=>{const q=words(query),d=words(record.description??'');let hits=0;for(const w of q)if(d.has(w))hits++;return hits/q.size+(preferred.get(record.dataType)??0)/100};
const used=new Set(),foods=[],resolution=[];
for(const descriptor of manifest.foods){const ranked=records.map(record=>({record,score:score(descriptor,record)})).filter(x=>x.score>=.70).sort((a,b)=>b.score-a.score);const winner=ranked.find(x=>!used.has(x.record.fdcId));if(!winner){resolution.push({descriptor,status:'unresolved',reason:'No sufficiently matching Foundation/SR/FNDDS record in supplied official export.'});continue}const r=winner.record;used.add(r.fdcId);const nutrients={};const provenance={};for(const entry of r.foodNutrients??[]){const id=entry.nutrient?.id??entry.nutrientId;const mapped=nutrientMap.get(id);if(!mapped)continue;const [key,unit]=mapped,actual=String(entry.nutrient?.unitName??entry.unitName??'').replace(/^UG$/i,'µg').toLowerCase().replace('µg','µg');const amount=entry.amount;if(actual!==unit.toLowerCase()||!Number.isFinite(amount)||amount<=0)continue;nutrients[key]=amount;provenance[key]={evidenceId:`fdc:${r.fdcId}`,fdcNutrientId:id,unit,amountPer100g:amount}}if(!Object.hasOwn(nutrients,'energy')){resolution.push({descriptor,status:'unresolved',reason:`FDC ${r.fdcId} lacks a positive mapped energy value.`});used.delete(r.fdcId);continue}const rawCookedBasis=basis(r.description);foods.push({id:`fdc-${r.fdcId}`,fdcId:r.fdcId,name:r.description,category:r.foodCategory?.description??r.foodCategory??'USDA food',dataType:r.dataType,publicationDate:r.publicationDate??null,rawCookedBasis,preparations:[{method:rawCookedBasis,basis:rawCookedBasis,yield:null,retention:{},evidenceId:`fdc:${r.fdcId}`}],nutrients,provenance});resolution.push({descriptor,status:'resolved',fdcId:r.fdcId,description:r.description,dataType:r.dataType})}
const output={schemaVersion:1,status:resolution.some(x=>x.status==='unresolved')?'partial':'complete',source:{name:'USDA FoodData Central',official:true,importedAt:new Date().toISOString(),input:inputPath},nutrientForms:canonicalForms,foods,targets};await writeFile(outputPath,JSON.stringify(output,null,2)+'\n');await writeFile(reportPath,JSON.stringify({generatedAt:new Date().toISOString(),input:inputPath,total:manifest.foods.length,resolved:foods.length,unresolved:resolution.filter(x=>x.status==='unresolved').length,entries:resolution},null,2)+'\n');if(foods.length!==manifest.foods.length){console.error(`Resolved ${foods.length}/${manifest.foods.length}; see ${reportPath}`);process.exitCode=1}else console.log(`Imported ${foods.length} traceable FDC foods to ${outputPath}`);
