-- Evidence audit for the two condition models. All rows remain disabled because none supplies
-- a transferable individual meal-absorption coefficient for this calculator's healthy ranges.
insert into evidence_sources(id,title,organization,url,publication_year,source_type,population,notes) values
 ('marcuard-1994','Proton pump inhibitors and the absorption of cobalamin','Journal of Clinical Gastroenterology','https://pubmed.ncbi.nlm.nih.gov/8276393/',1994,'human-study','10 healthy volunteers receiving omeprazole','Acute protein-bound cobalamin absorption test decreased during pharmacological acid suppression. The study did not validate a dietary coefficient for diagnosed hypochlorhydria, usual food doses, free/crystalline B12, or long-term status.'),
 ('celiac-nutrition-review-2019','Nutritional Imbalances in Adult Celiac Disease','Nutrients','https://doi.org/10.3390/nu11122968',2019,'review','adults with untreated and treated celiac disease','Reports heterogeneous nutrient status and intake findings. Deficiency prevalence and serum concentration are not meal-absorption coefficients.'),
 ('celiac-followup-guideline-2023','ACG Clinical Guideline: Diagnosis and Management of Celiac Disease','American Journal of Gastroenterology','https://doi.org/10.14309/ajg.0000000000002075',2023,'guideline','people with celiac disease','Recommends assessment/correction of micronutrient deficiencies. It does not specify nutrient-specific dietary absorption multipliers.')
on conflict(id) do nothing;

insert into model_assumptions(model_key,description,formula,parameters_json,conditions_json,limitations,status,evidence_id,classification,confidence,enabled) values
 ('b12.food_bound.pii_acid_suppression.v1','Food-bound B12 under pharmacological acid suppression',null,'{}','{"condition":"acid_suppression","form":"food_bound"}','A small acute human protein-bound B12 test is not a compatible coefficient for the calculator''s 30–60% healthy food model, documented hypochlorhydria, or free/crystalline B12.','unsupported','marcuard-1994','F','low',false),
 ('iron.nonheme.hypochlorhydria.v1','Non-heme iron handling in hypochlorhydria',null,'{}','{"condition":"hypochlorhydria","form":"nonheme"}','Human evidence supports acid-dependent solubilization, but no validated individual dietary non-heme absorption coefficient/range was identified. Heme iron is not included.','unsupported','hurrell-egli-2010','F','low',false),
 ('celiac.active.mucosal-malabsorption.v1','Active celiac nutrient malabsorption',null,'{}','{"condition":"celiac_disease","state":"active_untreated","nutrients":["iron","folate","vitamin_b12","vitamin_d","calcium","zinc","magnesium"]}','Clinical deficiency, biopsy, intake, and serum data are heterogeneous and do not establish a transferable nutrient/form-specific meal-absorption coefficient.','unsupported','celiac-followup-guideline-2023','F','moderate',false),
 ('celiac.treated.recovery.v1','Treated adherent celiac mucosal recovery',null,'{}','{"condition":"celiac_disease","state":"treated_adherent"}','Recovery varies by adherence, time, mucosal healing and intake. No permanent penalty or individual normalization coefficient is defensible.','unsupported','celiac-nutrition-review-2019','F','low',false)
on conflict(model_key) do nothing;
