-- PEI and bariatric-surgery evidence audit. All candidate records in this migration are
-- intentionally disabled: the reviewed human evidence establishes mechanisms, status
-- risk, or clinical management, but not a nutrient/form-specific meal coefficient that
-- can be transferred to this calculator.
insert into evidence_sources(id,title,organization,url,publication_year,source_type,population,notes) values
 ('aga-epi-update-2023','AGA Clinical Practice Update on the Epidemiology, Evaluation, and Management of Exocrine Pancreatic Insufficiency','American Gastroenterological Association','https://doi.org/10.1053/j.gastro.2023.02.012',2023,'guideline','adults with suspected or confirmed exocrine pancreatic insufficiency','Defines PEI as impaired pancreatic enzyme activity causing maldigestion; recommends objective evaluation and pancreatic enzyme replacement therapy when PEI is diagnosed. It does not provide nutrient/form-specific dietary fat or fat-soluble-vitamin absorption/restoration fractions.'),
 ('pei-nutrition-review-2019','Nutrition in pancreatic diseases: a road map for the gastroenterologist','United European Gastroenterology Journal','https://doi.org/10.1177/2050640619870351',2019,'review','people with pancreatic diseases and pancreatic exocrine insufficiency','Reviews risk of fat-soluble vitamin and other micronutrient deficiency/status abnormalities. Heterogeneous status, disease, and intake findings are not meal-level absorption, loss, or requirement coefficients.'),
 ('asmbs-nutrition-guidelines-2016','American Society for Metabolic and Bariatric Surgery Integrated Health Nutritional Guidelines for the Surgical Weight Loss Patient—2016 Update: Micronutrients','American Society for Metabolic and Bariatric Surgery','https://doi.org/10.1016/j.soard.2016.12.018',2017,'guideline','adults after bariatric procedures','Procedure-specific screening and supplementation recommendations for RYGB, sleeve gastrectomy, and BPD/DS. Recommended intake/supplements and postoperative deficiency prevalence do not quantify a personal oral absorption fraction or requirement equation.'),
 ('bomss-monitoring-2020','British Obesity and Metabolic Surgery Society Guidelines on perioperative and postoperative biochemical monitoring and micronutrient replacement','Obesity Reviews','https://doi.org/10.1111/obr.13087',2020,'guideline','adults after bariatric procedures','Supports procedure-specific follow-up and biochemical monitoring. It does not establish a generic or transferable post-operative nutrient multiplier.')
on conflict(id) do nothing;

insert into model_assumptions(model_key,description,formula,parameters_json,conditions_json,limitations,status,evidence_id,classification,confidence,enabled) values
 ('pei.fat-digestion.v1','PEI dietary fat and fat-soluble vitamin handling',null,'{}','{"condition":"pancreatic_exocrine_insufficiency","state":"documented_without_pert","nutrients":["vitamin_a","vitamin_d","vitamin_e","vitamin_k"],"stage":"digestion","endpoint":"clinical mechanism/status"}','PEI is a pancreatic digestion mechanism, not a general intestinal absorption coefficient. No transferable dietary fat or vitamin A/D/E/K oral-dose fraction, severity curve, or personalized requirement equation was identified.','unsupported','aga-epi-update-2023','F','moderate',false),
 ('pei.pert-nutrient-restoration.v1','PERT restoration of dietary nutrient handling in PEI',null,'{}','{"condition":"pancreatic_exocrine_insufficiency","state":"documented_with_pert","nutrients":["vitamin_a","vitamin_d","vitamin_e","vitamin_k"],"stage":"digestion","endpoint":"clinical-use guidance"}','PERT guidance supports clinician-managed treatment of documented PEI, not a nutrient/form-specific restoration percentage. It is not assumed to normalize absorption.','unsupported','aga-epi-update-2023','F','moderate',false),
 ('pei.micronutrient-status.v1','PEI B12, calcium, magnesium, and zinc handling',null,'{}','{"condition":"pancreatic_exocrine_insufficiency","nutrients":["vitamin_b12","calcium","magnesium","zinc"],"stage":"systemic","endpoint":"deficiency/status"}','Observed status risk cannot be converted to absorption, loss, conversion, or requirement coefficients.','unsupported','pei-nutrition-review-2019','F','low',false),
 ('rygb.micronutrient-handling.v1','RYGB micronutrient handling',null,'{}','{"condition":"bariatric_bypass","procedure":"rygb","nutrients":["iron","vitamin_b12","calcium","vitamin_d"],"endpoint":"guidance/status/heterogeneous studies"}','RYGB anatomy supports distinct qualitative mechanisms, but no transferable individual nutrient/form-specific meal coefficient or time-response curve is enabled.','unsupported','asmbs-nutrition-guidelines-2016','F','moderate',false),
 ('sg.micronutrient-handling.v1','Sleeve-gastrectomy micronutrient handling',null,'{}','{"condition":"bariatric_bypass","procedure":"sleeve_gastrectomy","nutrients":["iron","vitamin_b12","calcium","vitamin_d"],"endpoint":"guidance/status"}','Sleeve is not treated as intestinal bypass. No transferable nutrient/form-specific coefficient is enabled.','unsupported','asmbs-nutrition-guidelines-2016','F','moderate',false),
 ('bpd_ds.micronutrient-handling.v1','BPD/DS micronutrient handling',null,'{}','{"condition":"bariatric_bypass","procedure":"bpd_ds","nutrients":["vitamin_a","vitamin_d","vitamin_e","vitamin_k","calcium","iron","vitamin_b12","zinc","copper","magnesium"],"endpoint":"guidance/status"}','BPD/DS is not assigned an RYGB coefficient. Procedure-specific risk and guidance do not yield a transferable dietary fat or micronutrient coefficient.','unsupported','asmbs-nutrition-guidelines-2016','F','moderate',false)
on conflict(model_key) do nothing;

update clinical_conditions set description='Select documented PEI and enzyme-replacement context only; no symptom-based severity or restoration percentage is inferred.',evidence_id='aga-epi-update-2023',input_schema='["state: documented_without_pert|documented_with_pert"]'::jsonb where id='pancreatic_exocrine_insufficiency';
update clinical_conditions set description='Select the documented procedure: RYGB, sleeve gastrectomy, or BPD/DS. Procedure-specific clinical monitoring does not create an absorption multiplier.',evidence_id='asmbs-nutrition-guidelines-2016',input_schema='["procedure: rygb|sleeve_gastrectomy|bpd_ds"]'::jsonb where id='bariatric_bypass';

insert into condition_mechanisms(id,condition_id,physiological_process,model_stage,evidence_id,limitation) values
 ('pei.exocrine-fat-digestion','pancreatic_exocrine_insufficiency','Pancreatic enzyme-dependent fat digestion','digestion','aga-epi-update-2023','No individual dietary fat or fat-soluble-vitamin coefficient; requires documented PEI.'),
 ('pei.pert-clinical-context','pancreatic_exocrine_insufficiency','PERT clinical management context','digestion','aga-epi-update-2023','Clinical use is not a restoration percentage or medication dose.'),
 ('pei.micronutrient-status-monitoring','pancreatic_exocrine_insufficiency','Micronutrient status monitoring','systemic','pei-nutrition-review-2019','Status risk is not an absorption, loss, conversion, or requirement coefficient.'),
 ('rygb.iron-gastric-duodenal-handling','bariatric_bypass','RYGB gastric and proximal-intestinal iron handling','absorption','asmbs-nutrition-guidelines-2016','No heme/non-heme meal coefficient; overlaps low-acid mechanism and is not multiplied.'),
 ('rygb.b12-gastric-processing','bariatric_bypass','RYGB gastric B12 processing','absorption','asmbs-nutrition-guidelines-2016','No food-bound/free B12 coefficient; overlaps low-acid mechanism and is not multiplied.'),
 ('sg.b12-gastric-processing','bariatric_bypass','Sleeve gastric B12 processing','absorption','asmbs-nutrition-guidelines-2016','No intestinal-bypass mechanism is inferred.'),
 ('bpd_ds.fat-digestion-and-absorption','bariatric_bypass','BPD/DS fat digestion and handling','digestion','asmbs-nutrition-guidelines-2016','No transferable dietary fat or fat-soluble-vitamin coefficient.')
on conflict(id) do nothing;

insert into condition_recommendations(condition_id,mechanism_id,category,recommendation,rationale,evidence_id,evidence_strength,caution,clinician_supervision) values
 ('pancreatic_exocrine_insufficiency','pei.pert-clinical-context','clinician discussion','Discuss documented PEI and pancreatic-enzyme treatment context with the treating clinician.','PERT is clinician-managed for documented PEI; this application does not prescribe it or infer a nutrient restoration percentage.','aga-epi-update-2023','guideline','No medication dose, self-treatment recommendation, or nutrient-absorption guarantee is provided.',true),
 ('bariatric_bypass','rygb.iron-gastric-duodenal-handling','clinical follow-up','Discuss procedure-specific biochemical monitoring and supplementation planning with the bariatric follow-up team.','Postoperative supplementation guidance is separate from physiology and is not converted into an absorption coefficient.','asmbs-nutrition-guidelines-2016','guideline','No supplement dose or individualized physiological target is provided.',true)
on conflict do nothing;

-- Per-nutrient provenance remains explicitly non-numeric. These records cover every
-- executable catalog mechanism; `quantitative_model_key` and `coefficient_json` stay NULL.
insert into condition_nutrient_effects(mechanism_id,nutrient_id,effect_type,quantitative_model_key,coefficient_json,conditions_json,classification,confidence,evidence_id,limitation)
select mechanism_id,n.id,effect_type,null,null,conditions::jsonb,'F',confidence,evidence_id,limitation
from (values
 ('pei.exocrine-fat-digestion','vitamin_a','impaired_digestion','{"state":"documented_without_pert"}','moderate','aga-epi-update-2023','Digestion mechanism; no vitamin coefficient.'),
 ('pei.exocrine-fat-digestion','vitamin_d','impaired_digestion','{"state":"documented_without_pert"}','moderate','aga-epi-update-2023','Digestion mechanism; no vitamin coefficient.'),
 ('pei.exocrine-fat-digestion','vitamin_e','impaired_digestion','{"state":"documented_without_pert"}','moderate','aga-epi-update-2023','Digestion mechanism; no vitamin coefficient.'),
 ('pei.exocrine-fat-digestion','vitamin_k','impaired_digestion','{"state":"documented_without_pert"}','moderate','aga-epi-update-2023','Digestion mechanism; no vitamin coefficient.'),
 ('pei.pert-clinical-context','vitamin_a','clinical_management_context','{"state":"documented_with_pert"}','moderate','aga-epi-update-2023','No PERT restoration percentage.'),
 ('pei.micronutrient-status-monitoring','vitamin_b12','altered_systemic_availability','{}','low','pei-nutrition-review-2019','Status is not a coefficient.'),
 ('rygb.iron-gastric-duodenal-handling','iron','reduced_absorption','{"procedure":"rygb"}','moderate','asmbs-nutrition-guidelines-2016','No heme/non-heme coefficient.'),
 ('rygb.b12-gastric-processing','vitamin_b12','reduced_absorption','{"procedure":"rygb"}','moderate','asmbs-nutrition-guidelines-2016','No B12 form coefficient.'),
 ('rygb.calcium-proximal-intestinal-handling','calcium','reduced_absorption','{"procedure":"rygb"}','moderate','asmbs-nutrition-guidelines-2016','Guidance is not a coefficient.'),
 ('rygb.vitamin-d-status-monitoring','vitamin_d','altered_systemic_availability','{"procedure":"rygb"}','low','asmbs-nutrition-guidelines-2016','Status is not absorption.'),
 ('sg.b12-gastric-processing','vitamin_b12','reduced_absorption','{"procedure":"sleeve_gastrectomy"}','moderate','asmbs-nutrition-guidelines-2016','No B12 form coefficient.'),
 ('sg.iron-gastric-processing','iron','reduced_absorption','{"procedure":"sleeve_gastrectomy"}','moderate','asmbs-nutrition-guidelines-2016','No heme/non-heme coefficient.'),
 ('sg.micronutrient-status-monitoring','vitamin_d','altered_systemic_availability','{"procedure":"sleeve_gastrectomy"}','low','asmbs-nutrition-guidelines-2016','Status is not absorption.'),
 ('bpd_ds.fat-digestion-and-absorption','vitamin_a','impaired_digestion','{"procedure":"bpd_ds"}','moderate','asmbs-nutrition-guidelines-2016','No fat-soluble-vitamin coefficient.'),
 ('bpd_ds.proximal-nutrient-handling','iron','reduced_absorption','{"procedure":"bpd_ds"}','moderate','asmbs-nutrition-guidelines-2016','No form-specific coefficient.')
) as v(mechanism_id,nutrient_key,effect_type,conditions,confidence,evidence_id,limitation)
join nutrients n on n.canonical_key=v.nutrient_key
on conflict(mechanism_id,nutrient_id,effect_type) do nothing;
