-- Extends the initial normalized schema; reference rows remain canonical in Postgres.
create table food_composition_metadata (food_id uuid primary key references foods(id) on delete cascade, energy_kcal numeric check(energy_kcal >= 0), protein_g numeric check(protein_g >= 0), fat_g numeric check(fat_g >= 0), carbohydrate_g numeric check(carbohydrate_g >= 0), fiber_g numeric check(fiber_g >= 0), phytate_mg numeric check(phytate_mg >= 0), oxalate_mg numeric check(oxalate_mg >= 0), polyphenol_note text, data_source_id text references evidence_sources(id));
create table target_model_rules (id uuid primary key default gen_random_uuid(), nutrient_id uuid not null references nutrients(id), model_key text not null, parameters_json jsonb not null, conditions_json jsonb not null default '{}'::jsonb, evidence_id text references evidence_sources(id), is_heuristic boolean not null default false, unique(nutrient_id, model_key));
create table model_assumptions (id uuid primary key default gen_random_uuid(), model_key text unique not null, description text not null, formula text, parameters_json jsonb not null default '{}'::jsonb, limitations text not null, status text not null check(status in ('model_assumption','heuristic','unsupported')), evidence_id text references evidence_sources(id));
create table biomarker_definitions (id uuid primary key default gen_random_uuid(), marker_key text unique not null, marker_name text not null, default_unit text not null, compartment text, description text);
create table biomarker_reference_ranges (id uuid primary key default gen_random_uuid(), marker_id uuid not null references biomarker_definitions(id), sex text, age_min int, age_max int, low numeric, high numeric, evidence_id text references evidence_sources(id), check(low is null or high is null or low <= high));
create table biomarker_interpretation_rules (id uuid primary key default gen_random_uuid(), marker_id uuid not null references biomarker_definitions(id), nutrient_id uuid references nutrients(id), conditions_json jsonb not null default '{}'::jsonb, interpretation text not null, confidence text not null, evidence_id text references evidence_sources(id));
create table supplement_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, supplement_id uuid not null references supplements(id), amount numeric not null check(amount >= 0), unit text not null, taken_at timestamptz not null default now());
create table food_exclusions (user_id uuid not null references auth.users(id) on delete cascade, food_id uuid not null references foods(id), reason text, primary key(user_id, food_id));
alter table supplement_logs enable row level security; alter table food_exclusions enable row level security;
create policy "own supplement logs" on supplement_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own food exclusions" on food_exclusions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
